# create go webserver
FROM golang:1.20-alpine AS build

RUN mkdir /recibag
COPY . /recibag
WORKDIR /recibag

# Install dependencies
RUN apk add --no-cache git
RUN go mod tidy

RUN go build -o tmp/webserver src/cmd/webserver/main.go

FROM alpine:3.9

COPY --from=build /recibag/tmp/webserver bin/webserver

EXPOSE 50051

CMD ["bin/webserver"]